#! /bin/zsh
alias cfg="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"

cfg submodule init
cfg submodule update
cfg submodule foreach '\
    git fetch origin; \
    git checkout $(git rev-parse --abbrev-ref HEAD); \
    git reset --hard origin/$(git rev-parse --abbrev-ref HEAD); \
    git submodule update --recursive; \
    git clean -dfx; \
    git submodule init; \
    git pull origin $(git rev-parse --abbrev-ref HEAD)'