#!/usr/bin/env python3
import argparse
import os
import sys
from subprocess import DEVNULL, run

from pyfzf.pyfzf import FzfPrompt

DIRS = {
    "tmux": "share/tmux",
    "zsh": "share/zsh/plugins",
}
CFG = "/usr/bin/git --git-dir=$HOME/.cfg --work-tree=$HOME"
LOCAL = os.path.expanduser("~/.local")
SUB_ARGS = {"shell": True, "cwd": LOCAL, "capture_output": DEVNULL}


def get_dirs_help():
    dirs = ", ".join(DIRS.keys())
    return f"Possible arguments: {dirs}"


def main(args):
    folder = DIRS.get(args.folder, None)
    plugin_dirs = os.listdir(os.path.join(LOCAL, folder))
    fzf = FzfPrompt()
    try:
        names = fzf.prompt(plugin_dirs, "--multi --cycle")
    except Exception:
        sys.stderr.write("Aborted.\n")
        sys.exit(130)
    for name in names:
        path = os.path.join(folder, name)
        run(f"{CFG} submodule deinit -f {path}", **SUB_ARGS)
        run(f"{CFG} rm -rf {path}", **SUB_ARGS)
        run(f"{CFG} rm -rf {path}", **SUB_ARGS)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--folder", "-f", help=get_dirs_help(), required=True)
    args = parser.parse_args()
    main(args)